### ISSUE TITLE
Does it work with C++ too?

### ISSUE THREAD

**Issue by asb-capfan** [xsawyerx/xs-fun#18]
I guess this is really a dumb question but do you have fun with XS and C++  too?
Because, I like the OpenFST library (http://www.openfst.org) and would love to see at least some bindings in Perl, but it's written in C++, not C. 
XS fun in the other hand constantly talks about C++.

**Comment by xsawyerx** [comment]
@tsee Thank you for the comprehensive response.

I don't know how many in the club are from a C++ background, and we're mostly focusing on understand the core itself, which is C. However, one meeting to cover how these interact will probably be of interest to everyone (myself included). If you have the time, we'd love to hear it.
