### ISSUE TITLE
Chapter 01: I needed to do an extra `perl Makefile.PL` to get `make test` working.

### ISSUE THREAD

**Issue by d5ve** [xsawyerx/xs-fun#31]
When working through https://github.com/xsawyerx/xs-fun/blob/master/chapter_01/chapter_01.pod `make test` initially failed with `No tests defined for XSFun extension.`

Re-running `perl Makefile.PL` after creating `t/add_numbers.t` got `make test` working.

I guess that instruction should be in chapter_01.pod.

**Comment by paultcochrane** [comment]
@simbabque kindly added a fix for this issue; it should no longer be a problem.
